### ISSUE TITLE
Error: Couldn’t resolve Tailwind class name: container

### ISSUE THREAD

**Issue by dylandamsma** [lpbayliss/lpbayliss-nextjs-starter#3]
Hey Luke,

Sorry for the question, I am learning NextJS, Tailwind & Emotion and using your starter as example.

However, when using the `container` class as per defined in the TailwindCSS docs: https://tailwindcss.com/docs/container

I run into the following error:
```[ ready ] compiled successfully - ready on http://localhost:3000
[ error ] Error: Couldn’t resolve Tailwind class name: container
    at Object.e.resolveStyleFromPlugins (/Users/dylandamsma/Documents/smartinternmy/website-v3/node_modules/tailwind.macro/utils.umd.js:1:2242)
    at Module../components/menu/menu.component.tsx (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:299:155)
    at __webpack_require__ (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:23:31)
    at Module../components/menu/index.ts (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:236:73)
    at __webpack_require__ (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:23:31)
    at Module../components/index.ts (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:217:63)
    at __webpack_require__ (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:23:31)
    at Module../pages/_document.tsx (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:5435:69)
    at __webpack_require__ (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:23:31)
    at Object.0 (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:6004:18)
    at __webpack_require__ (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:23:31)
    at /Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:91:18
    at Object.<anonymous> (/Users/dylandamsma/Documents/smartinternmy/website-v3/.next/server/static/development/pages/_document.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```

Any idea how I could solve this?

**Comment by lpbayliss** [comment]
No need to apologise!

This error is coming from the ‘babel-plugin-tailwind’ package. It’s trying to resolve the container utility class but cannot find it.

I would;
* Check you have the alpha package installed (the one that works with tailwind v1)
* Check have the container configuration set up correctly in the tailwind configuration class.

If all looks in order I would start to investigate the package more specifically for potential bugs. Support for tailwind v1 is still alpha and very much a work in progress from what I can see.

I’d be curious to see how you were using the class in code? If you raise a PR with an example that reproduces the same error I can try and investigate also 🙂

**Comment by lpbayliss** [comment]
I ran a quick test using

```TypeScript
const Example = styled.div`
  ${tw`container`}
`;
```

I am getting;
![Snag_59398c8](https://user-images.githubusercontent.com/12537384/71935500-0b0a5400-31fb-11ea-80a8-de1cfe8b13c3.png)

The only other reference to this error I can find is [this issue](https://github.com/bradlc/babel-plugin-tailwind-components/issues/40). Given that this issue is using media queries, and the container uses the internally I have a feeling there is something going wrong with the break points.

**Comment by mike-niemand** [comment]
How was this resolved?
